# Generated by Django 3.1.2 on 2020-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='cover',
            field=models.ImageField(blank=True, upload_to='puzzles/'),
        ),
    ]
