# Generated by Django 3.1.2 on 2020-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20201009_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='question',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
    ]
