# Generated by Django 3.1.2 on 2020-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_puzzle_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
