# Generated by Django 3.1.2 on 2020-10-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_puzzle_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
    ]
